services:
  api:
    build: api
  
  client:
    build: client
  
  server:
    image: nginx:1.25-alpine
    ports:
      - 8080:80
    depends_on:
      - api
      - client
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
